name: DeployTerraform

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ github.workspace }}/appservice
    
    env:
      ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_ARM_TENNANT_ID }}    
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var "prefix=sample-dev"
        continue-on-error: true
  
      - name: Terraform Apply
        run: terraform apply -auto-approve -var "prefix=sample-dev"
  

      - name: 'Use Terraform Output'
        id: output
        run: |
         url=$(terraform output app_service_default_hostname)
         echo $url
         echo '::set-output name=app_url::$url'
         
      

      - name: 'teste'
        run: |
         echo ${{ steps.output.outputs.app_url  }}
